site_name: 'Finch'
site_description: 'An Open Source Container Development Tool'
repo_name: GitHub
repo_url: https://github.com/runfinch/finch
edit_uri: ""

nav:
  - Home:
      - "index.md"
      - Architecture:
          - "architecture/index.md"
  - Docs:
      - "docs/index.md"
      - Getting Started:
          - Installing Finch: "docs/getting-started/installation.md"
          - Building Images: "docs/getting-started/building-images.md"
          - Running Containers: "docs/getting-started/running-containers.md"
          - Pushing Images: "docs/getting-started/pushing-images.md"
          - Using Compose: "docs/getting-started/compose.md"
      - Managing Finch:
          - macOS:
             - Installation: "docs/managing-finch/macos/installation.md"
             - Disk Management: "docs/managing-finch/macos/disk-management.md"
             - Upgrading Finch: "docs/managing-finch/macos/upgrading-finch.md"
             - Uninstalling Finch: "docs/managing-finch/macos/uninstalling-finch.md"
          - Windows:
             - Installation: "docs/managing-finch/windows/installation.md"
             - WSL Configuration: "docs/managing-finch/windows/wsl-configuration.md"
             - Upgrading Finch: "docs/managing-finch/windows/upgrading-finch.md"
             - Uninstalling Finch: "docs/managing-finch/windows/uninstalling-finch.md"
          - Linux:
             - Installation: "docs/managing-finch/linux/installation.md"
             - Upgrading Finch: "docs/managing-finch/linux/upgrading-finch.md"
             - Uninstalling Finch: "docs/managing-finch/linux/uninstalling-finch.md"
             - Optional Components: "docs/managing-finch/linux/optional-components.md"
      - Container Images:
          - Registry Authentication: "docs/container-images/authentication.md"
          - Lazy Loading: "docs/container-images/lazy-loading.md"
          - Image Signing: "docs/container-images/signing-images.md"
      - Configuration Reference: "docs/configuration-reference.md"
      - Integrations:
          - DevContainers:
            - DevContainers on Finch: "docs/integrations/devcontainers-on-finch.md"
            - macOS: "docs/integrations/mac/devcontainers.md"
            - Windows: "docs/integrations/windows/devcontainers.md"
      - CLI Reference:
          - ... | flat | docs/cli-reference/*
      - Troubleshooting:
          - Getting Support: "docs/troubleshooting/get-support.md"
      - Release Notes: "docs/changelog.md"
  - Contributing:
      - Introduction: "contributing/index.md"

theme:
  name: 'material'
  logo: assets/logo.svg
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.ico
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: switch to light mode
  features:
    - navigation.indexes
    - navigation.sections
    - content.code.copy
    - content.tabs.link

copyright: Copyright &copy; Amazon 2023

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      alternate_style: true
  - toc:
      permalink: true

plugins:
  - search
  - awesome-pages
  - redirects:
      redirect_maps:
        'architecture/macos.md': 'architecture/index.md#macos'
