name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy docs
    if: ${{ github.repository == 'runfinch/finch-website' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@d77dd03172e96abbcdb081d8c948224762033653
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: runfinch.com
